"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert("Product", [
      {
        name: "럭비 맨투맨",
        gender: "남성",
        kind: "맨투맨",
        color: "블랙,퍼플,오렌지",
        image: "http://localhost:3001/image/럭비 맨투맨.jpg",
        price: 20000,
        discount: 15,
        count: 1,
      },
      {
        name: "이지 케어 레귤러핏 셔츠",
        gender: "남성",
        kind: "셔츠",
        color: "베이지,그린,블루",
        image: "http://localhost:3001/image/이지 케어 레귤러핏 셔츠.jpg",
        price: 130000,
        discount: 25,
        count: 1,
        sales: 50,
      },
      {
        name: "발수 카 코트",
        gender: "남성",
        kind: "아우터",
        color: "블랙,화이트,그린",
        image: "http://localhost:3001/image/발수 카 코트.jpg",
        price: 10000,
        discount: 10,
        count: 1,
      },
      {
        name: "레귤러 진",
        gender: "남성",
        kind: "데님",
        color: "블랙,베이지",
        image: "http://localhost:3001/image/레귤러 진.jpg",
        price: 50000,
        discount: 15,
        count: 1,
        sales: 100,
      },
      {
        name: "레귤러핏 조거 팬츠",
        gender: "남성",
        kind: "팬츠",
        color: "블랙,화이트,베이지",
        image: "http://localhost:3001/image/레귤러핏 조거 팬츠.jpg",
        price: 15000,
        discount: 20,
        count: 1,
        sales:30
      },
      {
        name: "지퍼 가디건",
        gender: "남성",
        kind: "가디건",
        color: "블랙,화이트,베이지",
        image: "http://localhost:3001/image/지퍼 가디건.jpg",
        price: 15000,
        discount: 20,
        count: 1,
        sales:30
      },
      {
        name: "더비슈즈",
        gender: "신발",
        kind: "가디건",
        color: "블랙,화이트,베이지",
        image: "http://localhost:3001/image/더비슈즈.jpg",
        price: 15000,
        discount: 20,
        count: 1,
        sales:30
      },
      {
        name: "오버사이즈코튼 집업후디",
        gender: "남성",
        kind: "후드티",
        color: "블랙,화이트,베이지,그레이",
        image: "http://localhost:3001/image/오버사이즈코튼 집업후디.jpg",
        price: 15000,
        discount: 20,
        count: 1,
        sales:30
      },
      {
        name: "레귤러핏 수트 팬츠",
        gender: "남성",
        kind: "수트",
        color: "블랙,화이트,베이지",
        image: "http://localhost:3001/image/레귤러핏 수트 팬츠.jpg",
        price: 15000,
        discount: 20,
        count: 1,
        sales:30
      },
      {
        name: "릴랙스핏 v넥 스웨터 베스트",
        gender: "남성",
        kind: "스웨터",
        color: "블랙,블루,브라운",
        image: "http://localhost:3001/image/릴랙스핏 v넥 스웨터 베스트.jpg",
        price: 15000,
        discount: 20,
        count: 1,
        sales:30
      },
      {
        name: "레귤러핏 텍스처 니트 스웨터",
        gender: "남성",
        kind: "니트",
        color: "블랙,화이트,베이지",
        image: "http://localhost:3001/image/레귤러핏 텍스처 니트 스웨터.jpg",
        price: 15000,
        discount: 20,
        count: 1,
        sales:30
      },
      {
        name: "프린트 스웨트 셔츠",
        gender: "남성",
        kind: "맨투맨",
        color: "블랙,퍼플,오렌지",
        image: "http://localhost:3001/image/프린트 스웨트 셔츠.jpg",
        price: 20000,
        discount: 15,
        count: 1,
      },
      {
        name: "릴랙스핏 옥스퍼드 셔츠",
        gender: "남성",
        kind: "셔츠",
        color: "베이지,그린,블루",
        image: "http://localhost:3001/image/릴랙스핏 옥스퍼드 셔츠.jpg",
        price: 130000,
        discount: 25,
        count: 1,
        sales:50
      },
      {
        name: "릴랙스핏 발수 코팅 카 코트",
        gender: "남성",
        kind: "아우터",
        color: "블랙,화이트,그린",
        image: "http://localhost:3001/image/릴랙스핏 발수 코팅 카 코트.jpg",
        price: 10000,
        discount: 10,
        count: 1,
      },
      {
        name: "루즈핏 진",
        gender: "남성",
        kind: "데님",
        color: "블랙,베이지",
        image: "http://localhost:3001/image/루즈핏 진.jpg",
        price: 50000,
        discount: 15,
        count: 1,
        sales:100,
      },
      {
        name: "코튼 치노 팬츠",
        gender: "남성",
        kind: "팬츠",
        color: "블랙,화이트,베이지",
        image: "http://localhost:3001/image/코튼 치노 팬츠.jpg",
        price: 15000,
        discount: 20,
        count: 1,
        sales:30
      },
      {
        name: "릴랙스핏 파인니트 가디건",
        gender: "남성",
        kind: "가디건",
        color: "블랙,화이트,베이지",
        image: "http://localhost:3001/image/릴랙스핏 파인니트 가디건.jpg",
        price: 15000,
        discount: 20,
        count: 1,
        sales:30
      },
      {
        name: "청키 스니커즈",
        gender: "신발",
        kind: "가디건",
        color: "블랙,화이트,베이지",
        image: "http://localhost:3001/image/청키 스니커즈.jpg",
        price: 15000,
        discount: 20,
        count: 1,
        sales:30
      },
      {
        name: "프린트후드티",
        gender: "남성",
        kind: "후드티",
        color: "블랙,화이트,베이지,그레이",
        image: "http://localhost:3001/image/프린트후드티.jpg",
        price: 15000,
        discount: 20,
        count: 1,
        sales:30
      },
      {
        name: "에센셜 블레이저",
        gender: "남성",
        kind: "수트",
        color: "블랙,화이트,베이지",
        image: "http://localhost:3001/image/에센셜 블레이저.jpg",
        price: 15000,
        discount: 20,
        count: 1,
        sales:30
      },
      {
        name: "슬림핏 터틀넥 스웨터",
        gender: "남성",
        kind: "스웨터",
        color: "블랙,화이트,베이지",
        image: "http://localhost:3001/image/슬림핏 터틀넥 스웨터.jpg",
        price: 15000,
        discount: 20,
        count: 1,
        sales:30
      },
      {
        name: "릴랙스핏 리브니트 스웨터",
        gender: "남성",
        kind: "니트",
        color: "블랙,화이트,베이지",
        image: "http://localhost:3001/image/릴랙스핏 리브니트 스웨터.jpg",
        price: 15000,
        discount: 20,
        count: 1,
        sales:30
      },
      {
        name: "프린트 맨투맨",
        gender: "여성",
        kind: "맨투맨",
        color: "블랙,퍼플,오렌지",
        image: "http://localhost:3001/image/프린트 맨투맨.jpg",
        price: 20000,
        discount: 15,
        count: 1,
      },
      {
        name: "크레이프 드레스",
        gender: "여성",
        kind: "드레스",
        color: "베이지,그린,블루",
        image: "http://localhost:3001/image/크레이프 드레스.jpg",
        price: 130000,
        discount: 25,
        count: 1,
        sales:50
      },
      {
        name: "더블 브레스티드 트렌치 코트",
        gender: "여성",
        kind: "아우터",
        color: "블랙,화이트,그린",
        image: "http://localhost:3001/image/더블 브레스티드 트렌치 코트.jpg",
        price: 10000,
        discount: 10,
        count: 1,
      },
      {
        name: "스키니 하이웨이스트 진",
        gender: "여성",
        kind: "데님",
        color: "블랙,베이지",
        image: "http://localhost:3001/image/스키니 하이웨이스트 진.jpg",
        price: 50000,
        discount: 15,
        count: 1,
        sales:100,
      },
      {
        name: "시가렛 팬츠",
        gender: "여성",
        kind: "팬츠",
        color: "블랙,화이트,베이지",
        image: "http://localhost:3001/image/시가렛 팬츠.jpg",
        price: 15000,
        discount: 20,
        count: 1,
        sales:30
      },
      {
        name: "파인 니트 가디건",
        gender: "여성",
        kind: "가디건",
        color: "블랙,화이트,베이지",
        image: "http://localhost:3001/image/파인 니트 가디건.jpg",
        price: 15000,
        discount: 20,
        count: 1,
        sales:30
      },
      {
        name: "청키 스니커즈",
        gender: "여성",
        kind: "신발",
        color: "블랙,화이트,베이지",
        image: "http://localhost:3001/image/청키 스니커즈.jpg",
        price: 15000,
        discount: 20,
        count: 1,
        sales:30
      },
      {
        name: "오버사이즈 후디",
        gender: "여성",
        kind: "후디",
        color: "블랙,화이트,베이지,그레이",
        image: "http://localhost:3001/image/오버사이즈 후디.jpg",
        price: 15000,
        discount: 20,
        count: 1,
        sales:30
      },
      {
        name: "피티드 티셔츠",
        gender: "여성",
        kind: "티셔츠",
        color: "블랙,화이트,베이지",
        image: "http://localhost:3001/image/피티드 티셔츠.jpg",
        price: 15000,
        discount: 20,
        count: 1,
        sales:30
      },
      {
        name: "리브니트 스웨터",
        gender: "여성",
        kind: "스웨터",
        color: "블랙,블루,브라운",
        image: "http://localhost:3001/image/리브니트 스웨터.jpg",
        price: 15000,
        discount: 20,
        count: 1,
        sales:30
      },
      {
        name: "파인니트 탑",
        gender: "여성",
        kind: "탑",
        color: "블랙,화이트,베이지",
        image: "http://localhost:3001/image/파인니트 탑.jpg",
        price: 15000,
        discount: 20,
        count: 1,
        sales:30
      },
      {
        name: "프린트 오버사이즈 맨투맨",
        gender: "여성",
        kind: "맨투맨",
        color: "블랙,퍼플,오렌지",
        image: "http://localhost:3001/image/프린트 오버사이즈 맨투맨.jpg",
        price: 20000,
        discount: 15,
        count: 1,
      },
      {
        name: "코튼 바디콘 드레스",
        gender: "여성",
        kind: "드레스",
        color: "베이지,그린,블루",
        image: "http://localhost:3001/image/코튼 바디콘 드레스.jpg",
        price: 130000,
        discount: 25,
        count: 1,
        sales:50
      },
      {
        name: "패딩 보머 재킷",
        gender: "여성",
        kind: "아우터",
        color: "블랙,화이트,그린",
        image: "http://localhost:3001/image/패딩 보머 재킷.jpg",
        price: 10000,
        discount: 10,
        count: 1,
      },
      {
        name: "로라이즈 배기 진",
        gender: "여성",
        kind: "데님",
        color: "블랙,베이지",
        image: "http://localhost:3001/image/로라이즈 배기 진.jpg",
        price: 50000,
        discount: 15,
        count: 1,
        sales:100,
      },
      {
        name: "코튼 블렌드 스웨트 팬츠",
        gender: "여성",
        kind: "팬츠",
        color: "블랙,화이트,베이지",
        image: "http://localhost:3001/image/코튼 블렌드 스웨트 팬츠.jpg",
        price: 15000,
        discount: 20,
        count: 1,
        sales:30
      },
      {
        name: "비스코스 블렌드 가디건",
        gender: "여성",
        kind: "가디건",
        color: "블랙,화이트,베이지",
        image: "http://localhost:3001/image/비스코스 블렌드 가디건.jpg",
        price: 15000,
        discount: 20,
        count: 1,
        sales:30
      },
      {
        name: "청키 로퍼",
        gender: "여성",
        kind: "신발",
        color: "블랙,화이트,베이지",
        image: "http://localhost:3001/image/청키 로퍼.jpg",
        price: 15000,
        discount: 20,
        count: 1,
        sales:30
      },
      {
        name: "오버사이즈 집업 후디",
        gender: "여성",
        kind: "후디",
        color: "블랙,화이트,베이지,그레이",
        image: "http://localhost:3001/image/오버사이즈 집업 후디.jpg",
        price: 15000,
        discount: 20,
        count: 1,
        sales:30
      },
      {
        name: "오버사이즈 티셔츠",
        gender: "여성",
        kind: "티셔츠",
        color: "블랙,화이트,베이지",
        image: "http://localhost:3001/image/오버사이즈 티셔츠.jpg",
        price: 15000,
        discount: 20,
        count: 1,
        sales:30
      },
      {
        name: "엠브로이더리 스웨터",
        gender: "여성",
        kind: "스웨터",
        color: "블랙,블루,브라운",
        image: "http://localhost:3001/image/엠브로이더리 스웨터.jpg",
        price: 15000,
        discount: 20,
        count: 1,
        sales:30
      },
      {
        name: "오버사이즈 저지 탑",
        gender: "여성",
        kind: "탑",
        color: "블랙,오렌지,네이비",
        image: "http://localhost:3001/image/오버사이즈 저지 탑.jpg",
        price: 15000,
        discount: 20,
        count: 1,
        sales: 30,
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete("Product", null, {});
  },
};
